### ISSUE TITLE
Would be cool to get a badges badge for this

### ISSUE THREAD

**Issue by balupton** [npms-io/npms-badges#1]
This repository aims to be the definitive renderer of all the badges https://github.com/bevry/badges

It is also used by https://github.com/bevry/projectz for automatic injection of badges into readme files

Would you like to do it? Otherwise I could find some time in perhaps a few weeks.

**Comment by satazor** [comment]
Didn't know these projects, it would be nice to have npms.io badges integrated in them.

@balupton I'm kind of short on time, could you kindly work on it? Thanks in advance.

**Comment by balupton** [comment]
cool cross posted to https://github.com/bevry/badges/issues/6 - not sure when I will get to it, but will see what I can do, or perhaps someone else from our bevry community can jump on it 👍

**Comment by satazor** [comment]
Closing in favor of https://github.com/bevry/badges/issues/6
