### ISSUE TITLE
502 error on badges.npms.io

### ISSUE THREAD

**Issue by SkeLLLa** [npms-io/npms-badges#14]
https://badges.npms.io/* return 502. Is that service still available?

**Comment by satazor** [comment]
Yes, will look into it in a few minutes

**Comment by SkeLLLa** [comment]
It seems that it's down for a week or even more already.

**Comment by satazor** [comment]
Should be good now: https://badges.npms.io/cross-spawn.svg

Sorry!

**Comment by SkeLLLa** [comment]
Yeah. It's working. Thanks.
